### ISSUE TITLE
Is there a front desk project?

### ISSUE THREAD

**Issue by 625781186** [winterjung/drf-chat-server-example#1]

**Comment by winterjung** [comment]
Hi @625781186 ! What does "a front desk project" mean? It mean real world project?

**Comment by 625781186** [comment]
> Hi @625781186 ! What does "a front desk project" mean? It mean real world project?

Sorry , haha ,
it's mean `front-end project`,
such as `vue` or `react` project for this project.

**Comment by winterjung** [comment]
😭 Sorry I can't find any specific frontend project because I'm lack of frontend, but I think It should be exist somewhere...
